### ISSUE TITLE
Use Mimalloc instead of musl malloc

### ISSUE THREAD

**Issue by nwmcsween** [siderolabs/pkgs#1012]
Allocation heavy workloads will generally suffer with musl malloc due to it having different tradeoffs, replace it with mimalloc.

**Comment by smira** [comment]
Dup of #1010, feel free to re-open if you can clarify what you're looking for.

**Comment by nwmcsween** [comment]
Users could and generally do, there would be three separate categories though, malloc heavy program, malloc heavy system or memory heavy applications. KVM and Kubevirt for example would be considered memory heavy.

**Comment by smira** [comment]
Users run their workloads in containers, and not using host OS libc.

**Comment by nwmcsween** [comment]
> Users run their workloads in containers, and not using host OS libc.

Great point, I completely forgot about that part while thinking of the apps themselves.
