### ISSUE TITLE
Linux Socket Diag Subsystem

### ISSUE THREAD

**Issue by Preisschild** [siderolabs/pkgs#1028]
I just run into a problem with Cilium because it could not properly delete sockets. In the Cilium documentation it mentions that it depends on some kernel features:

https://docs.cilium.io/en/stable/network/kubernetes/kubeproxy-free/#limitations

> this functionality requires these kernel configs to be enabled: CONFIG_INET_DIAG, CONFIG_INET_UDP_DIAG and CONFIG_INET_DIAG_DESTROY.

I noticed that those properties were once enabled (Issue: https://github.com/siderolabs/talos/issues/6429, Commit: https://github.com/siderolabs/pkgs/commit/98ef0736130e660b95720db1ac23b7a6e1506f3e), but they are not anymore.

Is there a specific reason why this was disabled?

**Comment by frezbo** [comment]
seems to be a regression, probably enabling/disabling some config changed this

**Comment by frezbo** [comment]
Found the commit that changed: f4335dc45bc08910fc2ccdd429deb96acd602c48

**Comment by frezbo** [comment]
> Found the commit that changed: [f4335dc](https://github.com/siderolabs/pkgs/commit/f4335dc45bc08910fc2ccdd429deb96acd602c48)

it could have been by the KSPP recommendations or moving from 5.6 to 6.6 kernel
