### ISSUE TITLE
Build fails with unknown flag: --target

### ISSUE THREAD

**Issue by jbmorgado** [siderolabs/pkgs#538]
Trying to build with the instructions for the NVIDIA GPU module:
```
make kernel nonfree-kmod-nvidia PLATFORM=linux/amd64 PUSH=true
```

fails almost immediately with the error:
```
[I] ➜  make kernel nonfree-kmod-nvidia PLATFORM=linux/amd64 PUSH=true

make[1]: Entering directory '/home/user/code/siderolabs/pkgs'
make[2]: Entering directory '/home/user/code/siderolabs/pkgs'
unknown flag: --target
See 'docker --help'.
```

**Comment by frezbo** [comment]
it seems you don't have a buildkit runner yet, What does `docker buildx ls` show? If it's empty you'd need to create one by running `docker buildx create --use`

**Comment by deekue** [comment]
I was getting this from a version of Docker before `docker buildx` was added.  Upgrading to the latest docker-ce package and running the command frezbo mentions above got it working.
