### ISSUE TITLE
Kernel panic with 1.4

### ISSUE THREAD

**Issue by a-jeser** [siderolabs/pkgs#704]
Hello, 

I'm testing the v1.4.beta0 version of Talos Linux on my HomeLab, while the v1.3 version works fine.

The updated machine (x86_64) rebooted at each kernel startup. I guess it's a Kernel Panic, because with the `panic=0` argument, it doesn't reboot anymore.

Unfortunately, I don't have a console output on the monitor, to understand the Kernel Panic. FYI, I didn't have console output in v1.3.

**Comment by smira** [comment]
You might try `console=tty1` to get the console output. (default is `tty0`)

**Comment by a-jeser** [comment]
I have no more information with `console=tty1`.

**Comment by a-jeser** [comment]
I reused the Talos v1.3 kernel config file to compile the Linux kernel to version 6.1.22-talos. And now it does not kernel pan

For the output problem on the console, it seems to miss the linux-firmware `amdgpu`.

**Comment by a-jeser** [comment]
I found the module responsible for the Kernel Panic, it is `CONFIG_FB_NVIDIA`.

For the output problem on the console, I added in `nomodeset` in `extraKernelArgs` (in v1.4).

**Comment by smira** [comment]
Thanks for reporting this, probably we should remove it from the default config.
