### ISSUE TITLE
Nvidia Fabric Manager requires Nvidia driver to be of the same version

### ISSUE THREAD

**Issue by DpoBoceka** [siderolabs/pkgs#720]
After building proprietary driver there is an error from Fabric Manager service:
`fabric manager NVIDIA GPU driver interface version 525.85.12 don't match with driver version 530.41.03. Please update with matching NVIDIA driver package`.

It might make sense to release drivers based on [datacenter documentation](https://docs.nvidia.com/datacenter/tesla/index.html) in a bundle with FabricManager.

However, it seems there are several FTPs to download artifacts from:
1. https://download.nvidia.com/XFree86/ -- currently in use. This one misses some tesla drivers (aka datacenter), like **525.85.12**. I suspect the purpose of this FTP is to primarily serve drivers for desktops.
2. https://developer.download.nvidia.com/compute/nvidia-driver/redist/ -- this one has both FabricManager and x86 drivers(no arm64), but surprisingly enough does not serve a driver of version 525.85.12. It looks like this FTP might be an attempt to cover datacenter needs, but for some reasons there's inconsistency. Moreover, it does not have the latest version that's specified in datacenter docs - 525.105.17 - neither for FabricManager, nor for the driver.

But, using [Official Advanced Driver Search](https://www.nvidia.com/Download/Find.aspx) I can find that 525.105.17 driver, both for arm64 and x86, and I can download it from here: https://us.download.nvidia.com/tesla/525.105.17/NVIDIA-Linux-x86_64-525.105.17.run

And there's [fabric-manager-525](https://packages.ubuntu.com/source/jammy-updates/fabric-manager-525) of a required version in ubuntu packages, with original tars. I wonder where did they get it from...

---

That being said, I think it is rather undesirable to ship Talos even with mandatory pre-defined version of an OSS driver. Consider these examples:
1. Machines run "dated" GPUs which require driver **470.X.X** -- this driver is still well supported by Nvidia and the only limit is it's locked with CUDA 11.4. A classic example would be a popular Tesla K80. 
2. A newer version of an upstream **525.X.X** driver contains a bug and there's a need of a rollback, but it wouldn't make sense to rollback Talos version as well and be blocked by Nvidia in such case.

I would say, it basically means that maintaining a custom talos-installer would be __safer__ and more versatile, given everybody has different __supported__ hardware.

I think people deploy k8s on nodes with GPU for ML mostly, and if that's the case the only thing that matter is supported CUDA version, driver itself just needs to be stable enough.

**Comment by frezbo** [comment]
> Machines run "dated" GPUs which require driver 470.X.X -- this driver is still well supported by Nvidia and the only limit is it's locked with CUDA 11.4. A classic example would be a popular Tesla K80.

we don't plan to support 470 series officially unless it's some custom business contract

> A newer version of an upstream 525.X.X driver contains a bug and there's a need of a rollback, but it wouldn't make sense to rollback Talos version as well and be blocked by Nvidia in such case.

so the plan is to ship the latest driver version that supports both fabricmanager and normal ones. So if we have version X > Y, but X doesn;t have matching fabric manager, we'll stick with Y.
