### ISSUE TITLE
Help with Deploying NVIDIA device plugin

### ISSUE THREAD

**Issue by seedrick** [siderolabs/pkgs#721]
In the [Deploying NVIDIA device plugin](https://www.talos.dev/v1.4/talos-guides/configuration/nvidia-gpu-proprietary/#deploying-nvidia-device-plugin) section of the proprietary driver guide it says to apply a manifest--this is using `kubectl`, correct? The issue I have is that the contexts aren't propagated into kubeconfig, was I supposed to do that manually? If so, how?

**Comment by frezbo** [comment]
> the issue I have is that the contexts aren't propagated into kubeconfig

not sure what's the issue, you'd get the kubeconfig of a talos cluster using `talosctl kubeconfig` and it works
