### ISSUE TITLE
Enable USB Attached SCSI (UAS) driver

### ISSUE THREAD

**Issue by cehoffman** [siderolabs/pkgs#751]
The UAS driver allows for much better read and write performance and overcomes shortcomings in the bulk only transfer mode around command queueing and streaming. 

I believe it is as simple as enabling https://github.com/siderolabs/pkgs/blob/43451e68a0ddf634b90c7c12cca9437faa52d183/kernel/build/config-amd64#L4152C9-L4152C9 and I will be trying to build a custom Talos image with this enabled.

You can confirm the driver is loaded with `dmesg | grep usbcore` where you see a line like

> usbcore: registered new interface driver uas

**Comment by smira** [comment]
That would be cool to have it enabled, thanks!

**Comment by cehoffman** [comment]
After going through the menuconfig for the kernel following the custom kernel documentation, I noticed there is a divergence between ARM64 and AMD64 kernel configs related to USB. This is [already enabled](https://github.com/siderolabs/pkgs/blob/43451e68a0ddf634b90c7c12cca9437faa52d183/kernel/build/config-arm64#L5269) on ARM64 along with several other USB drivers.

I was wondering if that divergence is a bug/unintended perhaps?

**Comment by smira** [comment]
Probably just an oversight, or it was enabled for ARM64 for some SBC, but missed for AMD64. You can simply make it `=y` and run `make kernel-olddefconfig` in the `pkgs` repo.
