### ISSUE TITLE
Drop `-pkg` suffixed images for in-tree kernel modules 

### ISSUE THREAD

**Issue by frezbo** [siderolabs/pkgs#805]
Drop `-pkg` suffixed images for in-tree kernel modules 

Extensions repo can base on the `kernel` image and just copy out files.

**Comment by frezbo** [comment]
hmm maybe `defconfig` needs to be run before

**Comment by frezbo** [comment]
> hmm maybe `defconfig` needs to be run before

this could be run in the extensions part, should still be fine, since adding an extension also runs depmod, this is almost an extra safety

**Comment by smira** [comment]
I don't think we need `modules.dep` in the extension itself since Talos runs `depmod` when building final `initramfs`. It was a problem early on, but shouldn't be a problem anymore.

**Comment by frezbo** [comment]
> I don't think we need `modules.dep` in the extension itself since Talos runs `depmod` when building final `initramfs`. It was a problem early on, but shouldn't be a problem anymore.

yes, i think it's fine, it was also to ship an extension that only has it's modules.dep, rather than one from the kernel-build, anyways we can still run this in extension, so not a big deal
