### ISSUE TITLE
Enable XDP in Kernel Config

### ISSUE THREAD

**Issue by goproslowyo** [siderolabs/pkgs#863]
Cilium has support for express data path but needs it enabled in the kernel and it doesn't currently appear that Talos Linux enables this configuration option. This is especially important while working at higher network speeds — 10 Gbps and above, which is becoming more commonplace as the standard in both enterprise and consumer gear.

https://docs.cilium.io/en/stable/operations/performance/tuning/#xdp-acceleration
https://docs.cilium.io/en/stable/network/kubernetes/kubeproxy-free/#xdp-acceleration

**Comment by Fizan324926** [comment]
is it paid?

**Comment by Fizan324926** [comment]
i have basic experience with xdp and eBPF and looking for the projects to contribute.

**Comment by smira** [comment]
`CONFIG_XDP_SOCKETS` is the kernel config option we're looking for
