### ISSUE TITLE
raspberrypi_firmware_version is old

### ISSUE THREAD

**Issue by anguslees** [siderolabs/pkgs#870]
Pkgfile says: `raspberrypi_firmware_version: 1.20230405`, which lacks support for rPi 5, in particular.

It seems the raspberrypi/firmware repo has stopped tagging 'releases', so I think talos needs to switch to using some other versioning scheme for this dependency.  Or alternatively, find another source for these files.

I can build my own custom image, but I think rPi-5 has sufficient visibility to warrant fixing this for everyone.

**Comment by smira** [comment]
@frezbo can you take a look please?

**Comment by frezbo** [comment]
probably renovate didn't pick it up
