### ISSUE TITLE
FR: Build kernel variant with DVB subsystem enabled

### ISSUE THREAD

**Issue by samip5** [siderolabs/pkgs#990]
It seems that the kernel config being used, is disabling all of dvb subsystem. This is not great for tuner cards.
Thus I'm requesting it to be enabled.

My tuner card is https://www.linuxtv.org/wiki/index.php/Hauppauge_WinTV-quadHD_(DVB-T/T2/C) which then uses cx23885 driver in kernel. This driver doesn't seem to be included nor is the dvb subsystem as a whole.

**Comment by smira** [comment]
This won't be included by default in the Talos kernel, as it's certainly a very niche requirement.

But you can prepare a PR with enabling required stuff as kernel modules, and push another to repackage as extensions. For example, https://github.com/siderolabs/extensions/tree/main/drivers/v4l-uvc

**Comment by samip5** [comment]
The patchset for the required things to enable for dvb is quite large, even when I tried to focus it on just my card.
Related: https://github.com/skyssolutions/talos-kernel/commit/598d30e1d2151cea062790736ebf4a12c41f302a

**Comment by samip5** [comment]
Fixed by #1102
